name: Build

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      BUNDLE_JOBS: 4
      BUNDLE_RETRY: 3
      CI: true
    strategy:
      fail-fast: false
      matrix:
        ruby: ["2.7"]
        gemfile: [
          "Gemfile"
        ]
        include:
        - ruby: "2.7"
          gemfile: "gemfiles/action_policy/master.gemfile"
        - ruby: "2.6"
          gemfile: "Gemfile"
        - ruby: "2.7"
          gemfile: "gemfiles/graphql/master.gemfile"
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      with:
        path: /home/runner/bundle
        key: bundle-${{ matrix.ruby }}-${{ matrix.gemfile }}-${{ hashFiles(matrix.gemfile) }}-${{ hashFiles('**/*.gemspec') }}
        restore-keys: |
          bundle-${{ matrix.ruby }}-${{ matrix.gemfile }}-
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler: ${{ matrix.bundler }}
    - name: Bundle install
      run: |
        bundle config path /home/runner/bundle
        bundle config --global gemfile ${{ matrix.gemfile }}
        bundle install
        bundle update
    - name: Run RSpec tests
      run: |
        bundle exec rspec --force-color
